# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:

- url: (.*)
  script: gameserver.app.app

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: free-ice-cream:europe-west1:free-ice-cream
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: foobar
    SQLALCHEMY_DATABASE_URI: >-
            mysql+mysqldb://root:foobar@localhost:3306/freeicecream
# [END env_variables]

beta_settings:
    cloud_sql_instances: free-ice-cream:europe-west1:free-ice-cream
